F
======================================================================
FAIL: test_max_profit_k_transactions (max_profit_k_transactions_testSuite.Test.test_max_profit_k_transactions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/max_profit_k_transactions_testSuite.py", line 6, in test_max_profit_k_transactions
    self.assertEqual(max_profit_with_k_transactions([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 10), 45)
AssertionError: 9 != 45

----------------------------------------------------------------------
Ran 1 test in 0.021s

FAILED (failures=1)
Command exited with non-zero status 1
	Command being timed: "python3 -m unittest discover -s . -p *test*.py"
	User time (seconds): 0.24
	System time (seconds): 0.17
	Percent of CPU this job got: 28%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.47
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 14592
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 2494
	Voluntary context switches: 121
	Involuntary context switches: 353
	Swaps: 0
	File system inputs: 0
	File system outputs: 576
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
