...F
======================================================================
FAIL: test_4 (max_subarray_sum_testSuite.TestMaxSubarraySum.test_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/max_subarray_sum_testSuite.py", line 15, in test_4
    self.assertEqual(max_subarray_sum([-6, -1]), -1)
AssertionError: 0 != -1

----------------------------------------------------------------------
Ran 4 tests in 0.044s

FAILED (failures=1)
Command exited with non-zero status 1
	Command being timed: "python3 -m unittest discover -s . -p *test*.py"
	User time (seconds): 0.19
	System time (seconds): 0.12
	Percent of CPU this job got: 22%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.39
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 14720
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 2489
	Voluntary context switches: 124
	Involuntary context switches: 320
	Swaps: 0
	File system inputs: 0
	File system outputs: 576
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
