EEEEE
======================================================================
ERROR: test_1 (find_second_largest_node_bst_testSuite.Test.test_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/find_second_largest_node_bst_testSuite.py", line 6, in test_1
    tree = TreeNode(5, TreeNode(3, TreeNode(1), TreeNode(4)), TreeNode(8, TreeNode(7), TreeNode(12, TreeNode(10, TreeNode(13)))))
           ^^^^^^^^
NameError: name 'TreeNode' is not defined

======================================================================
ERROR: test_2 (find_second_largest_node_bst_testSuite.Test.test_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/find_second_largest_node_bst_testSuite.py", line 11, in test_2
    tree = TreeNode(5, TreeNode(3, TreeNode(1), TreeNode(4)), TreeNode(8, TreeNode(7), TreeNode(12)))
           ^^^^^^^^
NameError: name 'TreeNode' is not defined

======================================================================
ERROR: test_3 (find_second_largest_node_bst_testSuite.Test.test_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/find_second_largest_node_bst_testSuite.py", line 16, in test_3
    tree = TreeNode(5, TreeNode(3, TreeNode(1), TreeNode(4)))
           ^^^^^^^^
NameError: name 'TreeNode' is not defined

======================================================================
ERROR: test_4 (find_second_largest_node_bst_testSuite.Test.test_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/find_second_largest_node_bst_testSuite.py", line 21, in test_4
    tree = TreeNode(5, TreeNode(3, TreeNode(1), TreeNode(4)), TreeNode(8, TreeNode(6, None, TreeNode(7))))
           ^^^^^^^^
NameError: name 'TreeNode' is not defined

======================================================================
ERROR: test_5 (find_second_largest_node_bst_testSuite.Test.test_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/find_second_largest_node_bst_testSuite.py", line 26, in test_5
    tree = TreeNode(5, TreeNode(3, TreeNode(1), TreeNode(4)), TreeNode(8, TreeNode(7), TreeNode(12, TreeNode(9, None, TreeNode(10, None, TreeNode(11))))))
           ^^^^^^^^
NameError: name 'TreeNode' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.035s

FAILED (errors=5)
Command exited with non-zero status 1
	Command being timed: "python3 -m unittest discover -s . -p *test*.py"
	User time (seconds): 0.20
	System time (seconds): 0.12
	Percent of CPU this job got: 35%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.91
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 14848
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 2488
	Voluntary context switches: 154
	Involuntary context switches: 183
	Swaps: 0
	File system inputs: 0
	File system outputs: 576
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
