F
======================================================================
FAIL: test_total_divisible_numbers (total_divisible_numbers_testSuite.Test.test_total_divisible_numbers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/total_divisible_numbers_testSuite.py", line 8, in test_total_divisible_numbers
    self.assertEqual(total_divisible_numbers([2, 3], 30), 30)
AssertionError: 5 != 30

----------------------------------------------------------------------
Ran 1 test in 0.014s

FAILED (failures=1)
Command exited with non-zero status 1
	Command being timed: "python3 -m unittest discover -s . -p *test*.py"
	User time (seconds): 0.21
	System time (seconds): 0.09
	Percent of CPU this job got: 31%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.98
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 14848
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 2487
	Voluntary context switches: 102
	Involuntary context switches: 302
	Swaps: 0
	File system inputs: 0
	File system outputs: 576
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
