FF
======================================================================
FAIL: test_1 (odd_even_ll_testSuite.Test.test_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/odd_even_ll_testSuite.py", line 8, in test_1
    self.assertEqual(print_ll(result), "1 -> 3 -> 5 -> 2 -> 4")
AssertionError: None != '1 -> 3 -> 5 -> 2 -> 4'

======================================================================
FAIL: test_2 (odd_even_ll_testSuite.Test.test_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/odd_even_ll_testSuite.py", line 12, in test_2
    self.assertEqual(print_ll(result), "2 -> 3 -> 6 -> 7 -> 1 -> 5 -> 4")
AssertionError: None != '2 -> 3 -> 6 -> 7 -> 1 -> 5 -> 4'

----------------------------------------------------------------------
Ran 2 tests in 0.045s

FAILED (failures=2)
1 -> 3 -> 5 -> 2 -> 4
2 -> 3 -> 6 -> 7 -> 1 -> 5 -> 4
Command exited with non-zero status 1
	Command being timed: "python3 -m unittest discover -s . -p *test*.py"
	User time (seconds): 0.36
	System time (seconds): 0.18
	Percent of CPU this job got: 38%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.44
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 14720
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 2488
	Voluntary context switches: 149
	Involuntary context switches: 249
	Swaps: 0
	File system inputs: 0
	File system outputs: 576
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
