..FF.
======================================================================
FAIL: test_3 (check_if_point_inside_polygon_testSuite.Test.test_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/check_if_point_inside_polygon_testSuite.py", line 12, in test_3
    self.assertTrue(check_if_point_inside_polygon([(0, 0), (3, 0), (3, 2), (0, 2)], (3, 1)))
AssertionError: False is not true

======================================================================
FAIL: test_4 (check_if_point_inside_polygon_testSuite.Test.test_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/check_if_point_inside_polygon_testSuite.py", line 15, in test_4
    self.assertTrue(check_if_point_inside_polygon([(0, 0), (3, 0), (3, 2), (0, 2)], (3, 0)))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 5 tests in 0.011s

FAILED (failures=2)
Command exited with non-zero status 1
	Command being timed: "python3 -m unittest discover -s . -p *test*.py"
	User time (seconds): 0.03
	System time (seconds): 0.01
	Percent of CPU this job got: 8%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.57
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 13952
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 2456
	Voluntary context switches: 187
	Involuntary context switches: 589
	Swaps: 0
	File system inputs: 0
	File system outputs: 576
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
