FF
======================================================================
FAIL: test_find_duplicates (find_duplicates_testSuite.Test.test_find_duplicates)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/find_duplicates_testSuite.py", line 7, in test_find_duplicates
    self.assertEqual(find_duplicates([1, 1, 1, 1]), [1])
AssertionError: {1} != [1]

======================================================================
FAIL: test_find_duplicates_2 (find_duplicates_testSuite.Test.test_find_duplicates_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/find_duplicates_testSuite.py", line 11, in test_find_duplicates_2
    self.assertEqual(find_duplicates_2([1, 1, 1, 1]), [1])
AssertionError: {1} != [1]

----------------------------------------------------------------------
Ran 2 tests in 0.079s

FAILED (failures=2)
Command exited with non-zero status 1
	Command being timed: "python3 -m unittest discover -s . -p *test*.py"
	User time (seconds): 0.20
	System time (seconds): 0.17
	Percent of CPU this job got: 31%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.18
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 14848
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 2489
	Voluntary context switches: 120
	Involuntary context switches: 482
	Swaps: 0
	File system inputs: 0
	File system outputs: 576
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
