F
======================================================================
FAIL: test_reverse_ll (reverse_ll_testSuite.Test.test_reverse_ll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/reverse_ll_testSuite.py", line 9, in test_reverse_ll
    self.assertEqual(print_ll(reverse_ll(build_ll([1, 2, 3, 4]))), '4 -> 3 -> 2 -> 1')
AssertionError: None != '4 -> 3 -> 2 -> 1'

----------------------------------------------------------------------
Ran 1 test in 0.009s

FAILED (failures=1)
4 -> 3 -> 2 -> 1
Command exited with non-zero status 1
	Command being timed: "python3 -m unittest discover -s . -p *test*.py"
	User time (seconds): 0.17
	System time (seconds): 0.10
	Percent of CPU this job got: 30%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.93
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 14848
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 2490
	Voluntary context switches: 124
	Involuntary context switches: 224
	Swaps: 0
	File system inputs: 0
	File system outputs: 576
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
